In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_wine
wine = load_wine()

In [ ]:
wine

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:                          1.36  3.23    2.36  0.27\n    Alcalinity of Ash:            10.6  30.0    19.5   3.3\n    Magnesium:                    70.0 162.0    99.7  14.3\n    Total Phenols:                0.98  3.88    2.29  0.63\n    Flavanoids:                   0.34  5.08    2.03  1.00\n    Nonflavanoid Phenols:         0.13  0.66    0.36  0.12\n    Proanthocyanins:              0.41  3.58    1.59  0.57\n    Colour Intensity:              1.3  13.0     5.1   2.3\n    Hue:                          0.48  1.71    0.96  0.23\n    OD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71\n    Proline:                       278  1680     746   315\n    ============================= ==== ===== ======= =====\n\n    :Missing Attribute Values: None\n    :Class Distribution: class_0 (59), class_1 (71), class_2 (48)\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThis is a copy of UCI ML Wine recognition datasets.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data\n\nThe data is the results of a chemical analysis of wines grown in the same\nregion in Italy by three different cultivators. There are thirteen different\nmeasurements taken for different constituents found in the three types of\nwine.\n\nOriginal Owners: \n\nForina, M. et al, PARVUS - \nAn Extendible Package for Data Exploration, Classification and Correlation. \nInstitute of Pharmaceutical and Food Analysis and Technologies,\nVia Brigata Salerno, 16147 Genoa, Italy.\n\nCitation:\n\nLichman, M. (2013). UCI Machine Learning Repository\n[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,\nSchool of Information and Computer Science. \n\n.. topic:: References\n\n  (1) S. Aeberhard, D. Coomans and O. de Vel, \n  Comparison of Classifiers in High Dimensional Settings, \n  Tech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of  \n  Mathematics and Statistics, James Cook University of North Queensland. \n  (Also submitted to Technometrics). \n\n  The data was used with many others for comparing various \n  classifiers. The classes are separable, though only RDA \n  has achieved 100% correct classification. \n  (RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data)) \n  (All results using the leave-one-out technique) \n\n  (2) S. Aeberhard, D. Coomans and O. de Vel, \n  "THE CLASSIFICATION PERFORMANCE OF RDA" \n  Tech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of \n  Mathematics and Statistics, James Cook University of North Queensland. \n  (Also submitted to Journal of Chemometrics).\n',
 'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'feature_names': ['alcohol',
  'malic_acid',
  'ash',
  'alcalinity_of_ash',
  'magnesium',
  'total_phenols',
  'flavanoids',
  'nonflavanoid_phenols',
  'proanthocyanins',
  'color_intensity',
  'hue',
  'od280/od315_of_diluted_wines',
  'proline'],
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2]),
 'target_names': array(['class_0', 'class_1', 'class_2'], dtype='<U7')}

In [ ]:
print("Inputs : ",wine.data)
print(wine.data.shape)
print("Input name : ",data.feature_names)
wine.feature_names = np.array(wine.feature_names)
print(wine.feature_names.shape)
print("Output : ",wine.target)
print(wine.target.shape)

Inputs :  [[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
(178, 13)
Input name :  ['alcohol' 'malic_acid' 'ash' 'alcalinity_of_ash' 'magnesium'
 'total_phenols' 'flavanoids' 'nonflavanoid_phenols' 'proanthocyanins'
 'color_intensity' 'hue' 'od280/od315_of_diluted_wines' 'proline']
(13,)
Output :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
(178,)

In [ ]:
df = pd.DataFrame(wine.data, columns = [wine.feature_names])
df['target'] = wine.target
df

    alcohol malic_acid   ash  ... od280/od315_of_diluted_wines proline target
0     14.23       1.71  2.43  ...                         3.92  1065.0      0
1     13.20       1.78  2.14  ...                         3.40  1050.0      0
2     13.16       2.36  2.67  ...                         3.17  1185.0      0
3     14.37       1.95  2.50  ...                         3.45  1480.0      0
4     13.24       2.59  2.87  ...                         2.93   735.0      0
..      ...        ...   ...  ...                          ...     ...    ...
173   13.71       5.65  2.45  ...                         1.74   740.0      2
174   13.40       3.91  2.48  ...                         1.56   750.0      2
175   13.27       4.28  2.26  ...                         1.56   835.0      2
176   13.17       2.59  2.37  ...                         1.62   840.0      2
177   14.13       4.10  2.74  ...                         1.60   560.0      2

[178 rows x 14 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaling = MinMaxScaler()

In [ ]:
dat = scaling.fit_transform(df[df.columns])
df = pd.DataFrame(dat)
df

           0         1         2         3   ...        10        11        12   13
0    0.842105  0.191700  0.572193  0.257732  ...  0.455285  0.970696  0.561341  0.0
1    0.571053  0.205534  0.417112  0.030928  ...  0.463415  0.780220  0.550642  0.0
2    0.560526  0.320158  0.700535  0.412371  ...  0.447154  0.695971  0.646933  0.0
3    0.878947  0.239130  0.609626  0.319588  ...  0.308943  0.798535  0.857347  0.0
4    0.581579  0.365613  0.807487  0.536082  ...  0.455285  0.608059  0.325963  0.0
..        ...       ...       ...       ...  ...       ...       ...       ...  ...
173  0.705263  0.970356  0.582888  0.510309  ...  0.130081  0.172161  0.329529  1.0
174  0.623684  0.626482  0.598930  0.639175  ...  0.178862  0.106227  0.336662  1.0
175  0.589474  0.699605  0.481283  0.484536  ...  0.089431  0.106227  0.397290  1.0
176  0.563158  0.365613  0.540107  0.484536  ...  0.097561  0.128205  0.400856  1.0
177  0.815789  0.664032  0.737968  0.716495  ...  0.105691  0.120879  0.201141  1.0

[178 rows x 14 columns]

In [ ]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [ ]:
class_0 = df[lambda v: v[13] == 0]
class_1 = df[lambda v: v[13] == 0.5]
class_2 = df[lambda v: v[13] == 1]

In [ ]:
print(class_0)

          0         1         2         3   ...        10        11        12   13
0   0.842105  0.191700  0.572193  0.257732  ...  0.455285  0.970696  0.561341  0.0
1   0.571053  0.205534  0.417112  0.030928  ...  0.463415  0.780220  0.550642  0.0
2   0.560526  0.320158  0.700535  0.412371  ...  0.447154  0.695971  0.646933  0.0
3   0.878947  0.239130  0.609626  0.319588  ...  0.308943  0.798535  0.857347  0.0
4   0.581579  0.365613  0.807487  0.536082  ...  0.455285  0.608059  0.325963  0.0
5   0.834211  0.201581  0.582888  0.237113  ...  0.463415  0.578755  0.835949  0.0
6   0.884211  0.223320  0.582888  0.206186  ...  0.439024  0.846154  0.721826  0.0
7   0.797368  0.278656  0.668449  0.360825  ...  0.471545  0.846154  0.725392  0.0
8   1.000000  0.177866  0.433155  0.175258  ...  0.487805  0.578755  0.547076  0.0
9   0.744737  0.120553  0.486631  0.278351  ...  0.430894  0.835165  0.547076  0.0
10  0.807895  0.280632  0.502674  0.381443  ...  0.626016  0.695971  0.878745  0.0
11  0.813158  0.146245  0.513369  0.319588  ...  0.560976  0.567766  0.714693  0.0
12  0.715789  0.195652  0.561497  0.278351  ...  0.544715  0.597070  0.743224  0.0
13  0.978947  0.195652  0.550802  0.041237  ...  0.626016  0.534799  0.621969  0.0
14  0.881579  0.223320  0.545455  0.072165  ...  0.585366  0.633700  0.905136  0.0
15  0.684211  0.211462  0.716578  0.340206  ...  0.650407  0.589744  0.736091  0.0
16  0.860526  0.233202  0.727273  0.484536  ...  0.479675  0.505495  0.714693  0.0
17  0.736842  0.164032  0.673797  0.484536  ...  0.528455  0.476190  0.607703  0.0
18  0.831579  0.167984  0.598930  0.304124  ...  0.609756  0.567766  1.000000  0.0
19  0.686842  0.466403  0.641711  0.237113  ...  0.390244  0.765568  0.404422  0.0
20  0.797368  0.175889  0.491979  0.278351  ...  0.495935  0.893773  0.358060  0.0
21  0.500000  0.604743  0.689840  0.412371  ...  0.447154  0.824176  0.350927  0.0
22  0.705263  0.221344  0.534759  0.309278  ...  0.512195  1.000000  0.539943  0.0
23  0.478947  0.169960  0.620321  0.371134  ...  0.495935  0.864469  0.525678  0.0
24  0.650000  0.211462  0.668449  0.484536  ...  0.520325  0.934066  0.404422  0.0
25  0.531579  0.258893  0.994652  0.742268  ...  0.528455  0.706960  0.393723  0.0
26  0.621053  0.203557  0.673797  0.283505  ...  0.357724  0.714286  0.654066  0.0
27  0.597368  0.193676  0.417112  0.329897  ...  0.439024  0.549451  0.718260  0.0
28  0.747368  0.229249  0.770053  0.453608  ...  0.626016  0.780220  0.454351  0.0
29  0.786842  0.185771  0.454545  0.278351  ...  0.455285  0.849817  0.539943  0.0
30  0.710526  0.150198  0.716578  0.613402  ...  0.577236  0.527473  0.718260  0.0
31  0.671053  0.181818  0.534759  0.438144  ...  0.495935  0.589744  0.882311  0.0
32  0.697368  0.215415  0.534759  0.340206  ...  0.609756  0.586081  0.507846  0.0
33  0.718421  0.156126  0.716578  0.458763  ...  0.626016  0.633700  0.682596  0.0
34  0.652632  0.209486  0.689840  0.432990  ...  0.504065  0.586081  0.582739  0.0
35  0.644737  0.211462  0.561497  0.510309  ...  0.455285  0.805861  0.457917  0.0
36  0.592105  0.177866  0.791444  0.252577  ...  0.495935  0.553114  0.429387  0.0
37  0.531579  0.179842  0.636364  0.381443  ...  0.520325  0.454212  0.589872  0.0
38  0.536842  0.150198  0.395722  0.252577  ...  0.569106  0.520147  0.529244  0.0
39  0.839474  0.642292  0.614973  0.134021  ...  0.333333  0.827839  0.343795  0.0
40  0.665789  0.191700  0.508021  0.288660  ...  0.382114  0.772894  0.368759  0.0
41  0.626316  0.612648  0.406417  0.422680  ...  0.349593  0.633700  0.539943  0.0
42  0.750000  0.227273  0.657754  0.226804  ...  0.325203  0.838828  0.582739  0.0
43  0.581579  0.640316  0.497326  0.355670  ...  0.276423  0.633700  0.286733  0.0
44  0.531579  0.203557  0.395722  0.329897  ...  0.325203  0.761905  0.432953  0.0
45  0.836842  0.652174  0.577540  0.427835  ...  0.317073  0.754579  0.572040  0.0
46  0.881579  0.563241  0.491979  0.278351  ...  0.455285  0.794872  0.561341  0.0
47  0.755263  0.185771  0.406417  0.278351  ...  0.349593  0.754579  0.504280  0.0
48  0.807895  0.252964  0.556150  0.422680  ...  0.479675  0.542125  0.557775  0.0
49  0.765789  0.195652  0.486631  0.350515  ...  0.520325  0.670330  0.700428  0.0
50  0.531579  0.195652  0.363636  0.092784  ...  0.520325  0.600733  0.621969  0.0
51  0.736842  0.179842  0.663102  0.340206  ...  0.617886  0.769231  0.703994  0.0
52  0.734211  0.199605  0.566845  0.175258  ...  0.430894  0.728938  0.650499  0.0
53  0.721053  0.229249  0.705882  0.335052  ...  0.528455  0.608059  0.782454  0.0
54  0.713158  0.183794  0.475936  0.298969  ...  0.357724  0.706960  0.557775  0.0
55  0.665789  0.195652  0.588235  0.510309  ...  0.406504  0.644689  0.600571  0.0
56  0.839474  0.189723  0.502674  0.293814  ...  0.373984  0.747253  0.493581  0.0
57  0.594737  0.243083  0.705882  0.319588  ...  0.479675  0.575092  0.707561  0.0
58  0.707895  0.136364  0.609626  0.314433  ...  0.333333  0.586081  0.718260  0.0

[59 rows x 14 columns]

In [ ]:
print(class_1)

           0         1         2         3   ...        10        11        12   13
59   0.352632  0.039526  0.000000  0.000000  ...  0.463415  0.201465  0.172611  0.5
60   0.342105  0.071146  0.491979  0.278351  ...  0.626016  0.146520  0.286733  0.5
61   0.423684  0.122530  0.352941  0.319588  ...  0.406504  0.117216  0.122682  0.5
62   0.694737  0.100791  0.299465  0.381443  ...  0.609756  0.435897  0.251070  0.5
63   0.352632  0.077075  0.427807  0.432990  ...  0.601626  0.586081  0.101284  0.5
..        ...       ...       ...       ...  ...       ...       ...       ...  ...
125  0.273684  0.280632  0.433155  0.536082  ...  0.308943  0.736264  0.071327  0.5
126  0.368421  0.156126  0.497326  0.561856  ...  0.170732  0.575092  0.052782  0.5
127  0.200000  0.274704  0.759358  0.922680  ...  0.398374  0.428571  0.134094  0.5
128  0.352632  0.175889  0.502674  0.716495  ...  0.333333  0.553114  0.045649  0.5
129  0.265789  0.703557  0.545455  0.587629  ...  0.252033  0.476190  0.215407  0.5

[71 rows x 14 columns]

In [ ]:
print(class_2)

           0         1         2         3   ...        10        11        12   13
130  0.481579  0.120553  0.513369  0.381443  ...  0.227642  0.007326  0.251070  1.0
131  0.486842  0.444664  0.556150  0.484536  ...  0.211382  0.054945  0.179743  1.0
132  0.468421  0.310277  0.556150  0.690722  ...  0.146341  0.032967  0.201141  1.0
133  0.439474  0.555336  0.534759  0.561856  ...  0.243902  0.007326  0.229672  1.0
134  0.389474  0.098814  0.475936  0.355670  ...  0.219512  0.087912  0.265335  1.0
135  0.413158  0.339921  0.449198  0.407216  ...  0.203252  0.113553  0.297432  1.0
136  0.321053  0.786561  0.631016  0.536082  ...  0.219512  0.000000  0.315264  1.0
137  0.394737  0.942688  0.684492  0.742268  ...  0.276423  0.153846  0.169044  1.0
138  0.647368  0.563241  0.443850  0.458763  ...  0.268293  0.201465  0.215407  1.0
139  0.476316  0.438735  0.668449  0.690722  ...  0.333333  0.322344  0.222539  1.0
140  0.500000  0.409091  0.716578  0.536082  ...  0.235772  0.380952  0.229672  1.0
141  0.613158  0.359684  0.529412  0.484536  ...  0.178862  0.439560  0.358060  1.0
142  0.655263  0.480237  0.727273  0.664948  ...  0.333333  0.289377  0.172611  1.0
143  0.681579  0.832016  0.529412  0.484536  ...  0.349593  0.285714  0.194009  1.0
144  0.321053  0.620553  0.449198  0.407216  ...  0.138211  0.267399  0.411555  1.0
145  0.560526  0.559289  0.422460  0.536082  ...  0.097561  0.150183  0.393723  1.0
146  0.750000  0.849802  0.465241  0.484536  ...  0.081301  0.021978  0.097718  1.0
147  0.484211  0.764822  0.598930  0.561856  ...  0.048780  0.216117  0.247504  1.0
148  0.602632  0.494071  0.545455  0.561856  ...  0.056911  0.128205  0.265335  1.0
149  0.539474  0.624506  0.534759  0.561856  ...  0.073171  0.021978  0.194009  1.0
150  0.650000  0.470356  0.673797  0.690722  ...  0.089431  0.010989  0.158345  1.0
151  0.463158  0.381423  0.598930  0.587629  ...  0.000000  0.073260  0.144080  1.0
152  0.547368  0.229249  0.743316  0.768041  ...  0.105691  0.021978  0.104850  1.0
153  0.578947  0.505929  0.491979  0.407216  ...  0.065041  0.087912  0.283167  1.0
154  0.407895  0.108696  0.395722  0.484536  ...  0.081301  0.102564  0.258203  1.0
155  0.563158  0.879447  0.513369  0.587629  ...  0.097561  0.076923  0.318830  1.0
156  0.739474  0.667984  0.545455  0.458763  ...  0.073171  0.135531  0.144080  1.0
157  0.373684  0.452569  0.684492  0.845361  ...  0.154472  0.168498  0.429387  1.0
158  0.871053  0.185771  0.716578  0.742268  ...  0.073171  0.252747  0.272468  1.0
159  0.644737  0.183794  0.684492  0.613402  ...  0.073171  0.186813  0.243937  1.0
160  0.350000  0.610672  0.545455  0.536082  ...  0.065041  0.113553  0.172611  1.0
161  0.700000  0.498024  0.631016  0.484536  ...  0.390244  0.201465  0.286733  1.0
162  0.478947  0.500000  0.652406  0.587629  ...  0.317073  0.307692  0.208274  1.0
163  0.507895  0.535573  0.529412  0.407216  ...  0.162602  0.175824  0.283167  1.0
164  0.723684  0.399209  0.502674  0.587629  ...  0.178862  0.150183  0.240371  1.0
165  0.710526  0.715415  0.481283  0.613402  ...  0.243902  0.175824  0.172611  1.0
166  0.636842  0.584980  0.663102  0.639175  ...  0.300813  0.106227  0.297432  1.0
167  0.471053  0.519763  0.502674  0.458763  ...  0.195122  0.175824  0.290300  1.0
168  0.671053  0.363636  0.711230  0.716495  ...  0.211382  0.194139  0.336662  1.0
169  0.623684  0.762846  0.802139  0.742268  ...  0.154472  0.238095  0.251070  1.0
170  0.307895  0.452569  0.513369  0.432990  ...  0.146341  0.205128  0.165478  1.0
171  0.457895  0.326087  0.491979  0.458763  ...  0.073171  0.131868  0.136947  1.0
172  0.823684  0.349802  0.598930  0.484536  ...  0.113821  0.161172  0.272468  1.0
173  0.705263  0.970356  0.582888  0.510309  ...  0.130081  0.172161  0.329529  1.0
174  0.623684  0.626482  0.598930  0.639175  ...  0.178862  0.106227  0.336662  1.0
175  0.589474  0.699605  0.481283  0.484536  ...  0.089431  0.106227  0.397290  1.0
176  0.563158  0.365613  0.540107  0.484536  ...  0.097561  0.128205  0.400856  1.0
177  0.815789  0.664032  0.737968  0.716495  ...  0.105691  0.120879  0.201141  1.0

[48 rows x 14 columns]

In [ ]:
df[13]

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
173    1.0
174    1.0
175    1.0
176    1.0
177    1.0
Name: 13, Length: 178, dtype: float64

In [ ]:
import numpy as np
def onehot(y):
  my = []
  for i in range(y.shape[0]):
    if y[i] == 0:
      my.append([1, 0, 0])
    if y[i] == 0.5:
      my.append([0, 1, 0])
    if y[i] == 1:
      my.append([0, 0, 1])

  my = np.array(my)

In [ ]:
onehot(df[13])

In [ ]:
X = data['data']
y = data['target']

In [ ]:
def perceptron(x_train, y_train):
 
  used_index = []
  weight = np.zeros(x_train.shape[1])# Intialize the weight randomly
  
  for i in range(0, x_train.shape[1]):
    weight[i] = 0.1 # random.uniform(0, 0.1)
  converged  = True
  
  while converged:
    print("Epoch:", epoch)
    hypothesis = np.dot(x_train[index], weight.T)
    if (y_train[index]==1 and hypothesis<0):
      
      weight = weight + x_train[index]
    if (y_train[index]==0 and hypothesis>=0):
      
      weight = weight - x_train[index]
    index = random.randint(0, x_train.shape[0]-1)     # pick the random sample
    used_index.append(index)
    if (len(set(used_index)) == x_train.shape[0]):
      
      score = predict(x_train, y_train, weight)
      if (score*100==100):
        print("Succefully Converged:")
        converged = False
    epoch = epoch + 1
  return weight

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])